### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by asdzheng** [DrizzleRisk/TUnpacker#1]
[*] Init env
Traceback (most recent call last):
  File "tunpacker.py", line 94, in <module>
    CheckEnv()
  File "tunpacker.py", line 27, in CheckEnv
    os.popen('adb root').readlines()[0].strip('\n')
IndexError: list index out of range

我的系统是win7,手机已root

**Comment by DrizzleRisk** [comment]
执行adb root只是保证接下来执行adb shell是以root权限执行，这里出错，应该是返回内容超过了一行，程序比较简单没有写异常处理，你可以尝试注释掉os.popen('adb root').readlines()[0].strip('\n') 这一行再试试（但是得你自己保证命令执行权限）。

——————更简单的方法————————
把.readlines()[0].strip('\n') 直接删除试一下

**Comment by asdzheng** [comment]
把readlines()[0].strip('\n') 直接删除了，出现其他错误：
[*] Get package info
Traceback (most recent call last):
  File "tunpacker.py", line 94, in <module>
    CheckEnv()
  File "tunpacker.py", line 44, in CheckEnv
    mfest = minidom.parseString(content)
  File "C:\Program Files (x86)\Python2.7\lib\xml\dom\minidom.py", line 1928, in
parseString
    return expatbuilder.parseString(string)
  File "C:\Program Files (x86)\Python2.7\lib\xml\dom\expatbuilder.py", line 940,
 in parseString
    return builder.parseString(string)
  File "C:\Program Files (x86)\Python2.7\lib\xml\dom\expatbuilder.py", line 223,
 in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by asdzheng** [comment]
这个好像是T家的，数字得用drizzleDumper么？

**Comment by DrizzleRisk** [comment]
错误是AXMLPrinter2.jar解析xml的问题引起的。你可以尝试用命令行调用AXMLPrinter2.jar试一下。
数字用drizzleDumper
